import service from '@/utils/request'

export const getTasks = (params) => service.get('/tasks', { params })
export const getTaskDetail = (taskId) => service.get(`/tasks/${taskId}`)
export const deleteTask = (taskId) => service.delete(`/tasks/${taskId}`)
export const retryTask = (taskId) => service.post(`/tasks/${taskId}/retry`)
export const cancelTask = (taskId) => service.post(`/tasks/${taskId}/cancel`)
export const pauseTask = (taskId) => service.post(`/tasks/${taskId}/pause`)
export const resumeTask = (taskId) => service.post(`/tasks/${taskId}/resume`)
export const updateTaskPriority = (taskId, priority) => service.put(`/tasks/${taskId}/priority`, { priority })
export const batchTaskAction = (action, taskIds) => service.post('/tasks/batch', { action, task_ids: taskIds })
export const retryAgent = (taskId) => service.post(`/tasks/${taskId}/agent-retry`)
export const retryAgentFile = (taskId, fileId) => service.post(`/tasks/${taskId}/agent-retry/${fileId}`)
export const cancelAgent = (taskId) => service.post(`/tasks/${taskId}/agent-cancel`)
export const exportTask = (taskId, format) => service.get(`/tasks/${taskId}/export`, { params: { format }, responseType: 'blob' })
export const getTaskResults = (taskId, params) => service.get(`/tasks/${taskId}/results`, { params })
export const getAgentResults = (taskId) => service.get(`/tasks/${taskId}/agent-results`)
export const compareTasks = (baselineTaskId, currentTaskId) => service.get('/analysis/compare', { params: { baseline_task_id: baselineTaskId, current_task_id: currentTaskId } })
export const getDashboardStats = (days = 7) => service.get('/dashboard/stats', { params: { days } })
