// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyCatalogImport(arg1) {
  return window['go']['main']['Service']['ApplyCatalogImport'](arg1);
}

export function CheckUncertain(arg1) {
  return window['go']['main']['Service']['CheckUncertain'](arg1);
}

export function CloseWarnings() {
  return window['go']['main']['Service']['CloseWarnings']();
}

export function ConfirmUncertain(arg1, arg2, arg3) {
  return window['go']['main']['Service']['ConfirmUncertain'](arg1, arg2, arg3);
}

export function ConnectDevice(arg1) {
  return window['go']['main']['Service']['ConnectDevice'](arg1);
}

export function DeleteHistoryFile(arg1, arg2) {
  return window['go']['main']['Service']['DeleteHistoryFile'](arg1, arg2);
}

export function DisconnectDevice(arg1) {
  return window['go']['main']['Service']['DisconnectDevice'](arg1);
}

export function DisconnectDeviceWithUploadPolicy(arg1, arg2) {
  return window['go']['main']['Service']['DisconnectDeviceWithUploadPolicy'](arg1, arg2);
}

export function EnqueueHistoryFile(arg1) {
  return window['go']['main']['Service']['EnqueueHistoryFile'](arg1);
}

export function ExportWindowLogs(arg1, arg2) {
  return window['go']['main']['Service']['ExportWindowLogs'](arg1, arg2);
}

export function GetAppSettings() {
  return window['go']['main']['Service']['GetAppSettings']();
}

export function GetCatalog() {
  return window['go']['main']['Service']['GetCatalog']();
}

export function GetCatalogFiles() {
  return window['go']['main']['Service']['GetCatalogFiles']();
}

export function GetDeviceStates() {
  return window['go']['main']['Service']['GetDeviceStates']();
}

export function GetDeviceStorage() {
  return window['go']['main']['Service']['GetDeviceStorage']();
}

export function GetKeywordHits(arg1, arg2) {
  return window['go']['main']['Service']['GetKeywordHits'](arg1, arg2);
}

export function GetUploadQueue(arg1) {
  return window['go']['main']['Service']['GetUploadQueue'](arg1);
}

export function GetUploadQueueBatches() {
  return window['go']['main']['Service']['GetUploadQueueBatches']();
}

export function GetUploadQueueStatus() {
  return window['go']['main']['Service']['GetUploadQueueStatus']();
}

export function ListHistory(arg1) {
  return window['go']['main']['Service']['ListHistory'](arg1);
}

export function LogFrontendError(arg1, arg2, arg3) {
  return window['go']['main']['Service']['LogFrontendError'](arg1, arg2, arg3);
}

export function LogPanic(arg1) {
  return window['go']['main']['Service']['LogPanic'](arg1);
}

export function OpenAppLogDirectory() {
  return window['go']['main']['Service']['OpenAppLogDirectory']();
}

export function OpenCatalogDirectory() {
  return window['go']['main']['Service']['OpenCatalogDirectory']();
}

export function OpenLogFolder(arg1) {
  return window['go']['main']['Service']['OpenLogFolder'](arg1);
}

export function ReadHistoryPreview(arg1) {
  return window['go']['main']['Service']['ReadHistoryPreview'](arg1);
}

export function ReloadCatalogFiles() {
  return window['go']['main']['Service']['ReloadCatalogFiles']();
}

export function ResetKeywordHits(arg1) {
  return window['go']['main']['Service']['ResetKeywordHits'](arg1);
}

export function RetryDeadBatch(arg1) {
  return window['go']['main']['Service']['RetryDeadBatch'](arg1);
}

export function RetryUncertain(arg1) {
  return window['go']['main']['Service']['RetryUncertain'](arg1);
}

export function ReusePreviousDeviceConfig(arg1) {
  return window['go']['main']['Service']['ReusePreviousDeviceConfig'](arg1);
}

export function SaveAppSettings(arg1) {
  return window['go']['main']['Service']['SaveAppSettings'](arg1);
}

export function SaveDeviceConfig(arg1, arg2) {
  return window['go']['main']['Service']['SaveDeviceConfig'](arg1, arg2);
}

export function SaveDeviceConfigWithResult(arg1, arg2) {
  return window['go']['main']['Service']['SaveDeviceConfigWithResult'](arg1, arg2);
}

export function SaveLogAs(arg1, arg2, arg3, arg4) {
  return window['go']['main']['Service']['SaveLogAs'](arg1, arg2, arg3, arg4);
}

export function ScanPorts() {
  return window['go']['main']['Service']['ScanPorts']();
}

export function SelectCatalogFile() {
  return window['go']['main']['Service']['SelectCatalogFile']();
}

export function SendCommand(arg1, arg2) {
  return window['go']['main']['Service']['SendCommand'](arg1, arg2);
}

export function SetDeviceConfigDirty(arg1, arg2) {
  return window['go']['main']['Service']['SetDeviceConfigDirty'](arg1, arg2);
}

export function StartTask(arg1) {
  return window['go']['main']['Service']['StartTask'](arg1);
}

export function StopTask(arg1) {
  return window['go']['main']['Service']['StopTask'](arg1);
}

export function SubscribeLogEvents(arg1) {
  return window['go']['main']['Service']['SubscribeLogEvents'](arg1);
}

export function SyncCloudKeywords() {
  return window['go']['main']['Service']['SyncCloudKeywords']();
}

export function UpdateDeviceConfig(arg1, arg2) {
  return window['go']['main']['Service']['UpdateDeviceConfig'](arg1, arg2);
}

export function ValidateDeviceConfig(arg1) {
  return window['go']['main']['Service']['ValidateDeviceConfig'](arg1);
}
