// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyCatalogImport(arg1:string):Promise<void>;

export function CloseWarnings():Promise<Array<string>>;

export function ConfirmUncertain(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ConnectDevice(arg1:main.DeviceConfigDTO):Promise<void>;

export function DeleteHistoryFile(arg1:string,arg2:boolean):Promise<void>;

export function DisconnectDevice(arg1:string):Promise<void>;

export function DisconnectDeviceWithUploadPolicy(arg1:string,arg2:boolean):Promise<void>;

export function EnqueueHistoryFile(arg1:string):Promise<void>;

export function ExportWindowLogs(arg1:string,arg2:string):Promise<string>;

export function GetAppSettings():Promise<main.AppSettingsDTO>;

export function GetCatalog():Promise<main.CatalogConfig>;

export function GetDeviceStates():Promise<Array<main.DeviceStateDTO>>;

export function GetDeviceStorage():Promise<Array<main.DeviceStorageDTO>>;

export function GetKeywordHits(arg1:string,arg2:string):Promise<Array<main.KeywordHitDTO>>;

export function GetUploadQueue(arg1:main.UploadQueueQueryDTO):Promise<main.UploadQueuePageDTO>;

export function GetUploadQueueBatches():Promise<Array<main.UploadBatchDTO>>;

export function GetUploadQueueStatus():Promise<main.QueueStatus>;

export function ListHistory(arg1:main.HistoryQueryDTO):Promise<main.HistoryPageDTO>;

export function LogFrontendError(arg1:string,arg2:string,arg3:string):Promise<void>;

export function LogPanic(arg1:any):Promise<void>;

export function OpenAppLogDirectory():Promise<void>;

export function OpenLogFolder(arg1:string):Promise<void>;

export function ReadHistoryPreview(arg1:string):Promise<main.HistoryPreviewDTO>;

export function ResetKeywordHits(arg1:string):Promise<void>;

export function RetryDeadBatch(arg1:string):Promise<void>;

export function RetryUncertain(arg1:string):Promise<void>;

export function SaveAppSettings(arg1:main.AppSettingsDTO):Promise<void>;

export function SaveDeviceConfig(arg1:string,arg2:main.DeviceConfigDTO):Promise<void>;

export function SaveDeviceConfigWithResult(arg1:string,arg2:main.DeviceConfigDTO):Promise<main.DeviceConfigSaveResult>;

export function SaveLogAs(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function ScanPorts():Promise<Array<main.PortInfo>>;

export function SelectCatalogFile():Promise<main.CatalogImportPreviewDTO>;

export function SendCommand(arg1:string,arg2:string):Promise<void>;

export function SetDeviceConfigDirty(arg1:string,arg2:boolean):Promise<void>;

export function StartTask(arg1:string):Promise<void>;

export function StopTask(arg1:string):Promise<void>;

export function SubscribeLogEvents(arg1:string):Promise<void>;

export function UpdateDeviceConfig(arg1:string,arg2:main.DeviceConfigDTO):Promise<void>;

export function ValidateDeviceConfig(arg1:main.DeviceConfigDTO):Promise<void>;
