// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyCatalogImport(arg1:string):Promise<void>;

export function CheckUncertain(arg1:string):Promise<main.UncertainCheckDTO>;

export function ClearUploadHistory():Promise<number>;

export function CloseWarnings():Promise<Array<string>>;

export function ConfirmUncertain(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ConnectDevice(arg1:main.DeviceConfigDTO):Promise<void>;

export function DeleteCatalogKeywordGroup(arg1:string,arg2:string):Promise<main.CatalogConfig>;

export function DeleteCatalogKeywordProfile(arg1:string):Promise<main.CatalogConfig>;

export function DeleteCatalogKeywordRule(arg1:string,arg2:string,arg3:string):Promise<main.CatalogConfig>;

export function DeleteCatalogProject(arg1:string):Promise<main.CatalogConfig>;

export function DeleteCatalogTask(arg1:string):Promise<main.CatalogConfig>;

export function DeleteHistoryFile(arg1:string,arg2:boolean):Promise<void>;

export function DeleteHistorySession(arg1:string,arg2:string):Promise<number>;

export function DisconnectDevice(arg1:string):Promise<void>;

export function DisconnectDeviceWithUploadPolicy(arg1:string,arg2:boolean):Promise<void>;

export function EnqueueHistoryFile(arg1:string):Promise<void>;

export function ExportWindowLogs(arg1:string,arg2:string):Promise<string>;

export function GetAppSettings():Promise<main.AppSettingsDTO>;

export function GetCatalog():Promise<main.CatalogConfig>;

export function GetCatalogFiles():Promise<main.CatalogFilesDTO>;

export function GetCurrentPendingUploadBytes(arg1:string):Promise<number>;

export function GetDeviceStates():Promise<Array<main.DeviceStateDTO>>;

export function GetDeviceStorage():Promise<Array<main.DeviceStorageDTO>>;

export function GetEditableConfigFile(arg1:string):Promise<main.EditableConfigFileDTO>;

export function GetKeywordHits(arg1:string,arg2:string):Promise<Array<main.KeywordHitDTO>>;

export function GetStartupWarnings():Promise<Array<string>>;

export function GetUploadQueue(arg1:main.UploadQueueQueryDTO):Promise<main.UploadQueuePageDTO>;

export function GetUploadQueueBatches():Promise<Array<main.UploadBatchDTO>>;

export function GetUploadQueueStatus():Promise<main.QueueStatus>;

export function ListHistory(arg1:main.HistoryQueryDTO):Promise<main.HistoryPageDTO>;

export function LogFrontendError(arg1:string,arg2:string,arg3:string):Promise<void>;

export function LogPanic(arg1:any):Promise<void>;

export function OpenAppLogDirectory():Promise<void>;

export function OpenCatalogDirectory():Promise<void>;

export function OpenLogFolder(arg1:string):Promise<void>;

export function ReadHistoryPreview(arg1:string):Promise<main.HistoryPreviewDTO>;

export function ReloadAppSettings():Promise<main.AppSettingsDTO>;

export function ReloadCatalogFiles():Promise<main.CatalogConfig>;

export function ResetKeywordHits(arg1:string):Promise<void>;

export function RetryDeadBatch(arg1:string):Promise<void>;

export function RetryUncertain(arg1:string):Promise<void>;

export function RetryUploadTask(arg1:main.UploadTaskDTO):Promise<main.UploadTaskActionResult>;

export function ReusePreviousDeviceConfig(arg1:string):Promise<main.DeviceConfigDTO>;

export function SaveAppSettings(arg1:main.AppSettingsDTO):Promise<void>;

export function SaveCatalogKeywordGroup(arg1:main.CatalogKeywordGroupInput):Promise<main.CatalogConfig>;

export function SaveCatalogKeywordProfile(arg1:main.CatalogKeywordProfileInput):Promise<main.CatalogConfig>;

export function SaveCatalogKeywordRule(arg1:main.CatalogKeywordRuleInput):Promise<main.CatalogConfig>;

export function SaveCatalogProject(arg1:main.CatalogProjectInput):Promise<main.CatalogConfig>;

export function SaveCatalogTask(arg1:main.CatalogTaskInput):Promise<main.CatalogConfig>;

export function SaveDeviceConfig(arg1:string,arg2:main.DeviceConfigDTO):Promise<void>;

export function SaveDeviceConfigWithResult(arg1:string,arg2:main.DeviceConfigDTO):Promise<main.DeviceConfigSaveResult>;

export function SaveEditableConfigFile(arg1:string,arg2:string):Promise<main.CatalogConfig>;

export function SaveLogAs(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function ScanPorts():Promise<Array<main.PortInfo>>;

export function SelectCatalogFile():Promise<main.CatalogImportPreviewDTO>;

export function SendCommand(arg1:string,arg2:string):Promise<void>;

export function SetDeviceConfigDirty(arg1:string,arg2:boolean):Promise<void>;

export function StartTask(arg1:string):Promise<void>;

export function StopTask(arg1:string):Promise<void>;

export function SubscribeLogEvents(arg1:string):Promise<void>;

export function SyncCloudConfig():Promise<main.CloudKeywordSyncResult>;

export function SyncCloudKeywords():Promise<main.CloudKeywordSyncResult>;

export function UpdateDeviceConfig(arg1:string,arg2:main.DeviceConfigDTO):Promise<void>;

export function ValidateDeviceConfig(arg1:main.DeviceConfigDTO):Promise<void>;
