<script setup>
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { Button, Checkbox, Empty, Form, FormItem, Input, Modal, Select, TabPane, Tabs, Tag, Tooltip } from 'ant-design-vue'
import { CloudSyncOutlined, DeleteOutlined, EditOutlined, FolderOpenOutlined, PlusOutlined, ReloadOutlined } from '@ant-design/icons-vue'

const props = defineProps({ catalog: { type: Object, default: () => ({ projects: [] }) }, invoke: Function })
const localCatalog = ref(props.catalog), files = ref(null), loading = ref(false), syncing = ref(false), message = ref('')
const dialog = reactive({ open: false, kind: '', editing: false })
const form = reactive({})
watch(() => props.catalog, (value) => { if (value?.projects) localCatalog.value = value }, { deep: true })
const projects = computed(() => localCatalog.value?.projects || [])
const tasks = computed(() => unique(projects.value.flatMap((x) => x.tasks || [])))
const profiles = computed(() => unique(tasks.value.flatMap((x) => x.keywordProfiles || [])))
function unique(items) { const map = new Map(); items.forEach((x) => { if (!map.has(x.id)) map.set(x.id, x) }); return [...map.values()] }
function rules(profile) { return [...(profile.rules || []), ...(profile.groups || []).flatMap((x) => x.rules || [])] }
function reset() { Object.assign(form, { id: '', name: '', versionsText: '', type: 'special', allProjects: true, applicableProjects: [], profileId: '', groupId: '', scope: '', match: '', mode: 'contains', caseSensitive: false }) }
function open(kind, value = {}, parent = {}) {
  reset(); Object.assign(dialog, { open: true, kind, editing: Boolean(value.id) })
  if (kind === 'project') Object.assign(form, { id: value.id || '', name: value.name || '', versionsText: (value.versions || []).join(', ') })
  if (kind === 'task') Object.assign(form, { id: value.id || '', name: value.name || '', type: value.type || 'special', allProjects: value.allProjects !== false, applicableProjects: value.applicableProjects || [] })
  if (kind === 'profile') Object.assign(form, { id: value.id || '', name: value.name || '' })
  if (kind === 'group') Object.assign(form, { profileId: parent.profileId, id: value.id || '', name: value.name || '', scope: value.scope || '' })
  if (kind === 'rule') Object.assign(form, { profileId: parent.profileId, groupId: parent.groupId || '', id: value.id || '', name: value.name || '', match: value.match || '', mode: value.mode || 'contains', caseSensitive: Boolean(value.caseSensitive) })
}
function dialogTitle() { return `${dialog.editing ? '编辑' : '新增'}${({ project: '项目', task: '任务', profile: '关键字方案', group: '关键字分类', rule: '关键字' })[dialog.kind]}` }
async function save() {
  const payload = dialog.kind === 'project' ? { id: form.id, name: form.name, versions: form.versionsText.split(/[,，\n]/).map((x) => x.trim()).filter(Boolean) }
    : dialog.kind === 'task' ? { id: form.id, name: form.name, type: form.type, allProjects: form.allProjects, applicableProjects: form.allProjects ? [] : form.applicableProjects }
      : dialog.kind === 'profile' ? { id: form.id, name: form.name }
        : dialog.kind === 'group' ? { profileId: form.profileId, id: form.id, name: form.name, scope: form.scope }
          : { profileId: form.profileId, groupId: form.groupId, id: form.id, name: form.name, match: form.match, mode: form.mode, caseSensitive: form.caseSensitive }
  const method = ({ project: 'SaveCatalogProject', task: 'SaveCatalogTask', profile: 'SaveCatalogKeywordProfile', group: 'SaveCatalogKeywordGroup', rule: 'SaveCatalogKeywordRule' })[dialog.kind]
  try { loading.value = true; localCatalog.value = await props.invoke(method, payload); dialog.open = false; await refreshFiles(); message.value = '已保存到本地配置文件' } catch (e) { message.value = `保存失败：${e.message || e}` } finally { loading.value = false }
}
function remove(kind, value, parent = {}) { Modal.confirm({ title: `删除${({ project: '项目', task: '任务', profile: '关键字方案', group: '关键字分类', rule: '关键字' })[kind]}`, content: `确认删除“${value.name}”？`, okType: 'danger', async onOk() { const method = ({ project: 'DeleteCatalogProject', task: 'DeleteCatalogTask', profile: 'DeleteCatalogKeywordProfile', group: 'DeleteCatalogKeywordGroup', rule: 'DeleteCatalogKeywordRule' })[kind]; const args = kind === 'group' ? [parent.profileId, value.id] : kind === 'rule' ? [parent.profileId, parent.groupId || '', value.id] : [value.id]; try { localCatalog.value = await props.invoke(method, ...args); await refreshFiles(); message.value = '已删除并写入本地配置文件' } catch (e) { message.value = `删除失败：${e.message || e}`; throw e } } }) }
async function refreshFiles() { files.value = await props.invoke('GetCatalogFiles') }
async function reloadCatalog() { try { loading.value = true; localCatalog.value = await props.invoke('ReloadCatalogFiles'); await refreshFiles(); message.value = '已重新读取程序目录下的配置文件' } catch (e) { message.value = `重新加载失败：${e.message || e}` } finally { loading.value = false } }
async function syncCloud() { try { syncing.value = true; const result = await props.invoke('SyncCloudConfig'); localCatalog.value = await props.invoke('GetCatalog'); await refreshFiles(); message.value = result?.message || '云端配置同步完成' } catch (e) { message.value = `同步失败：${e.message || e}` } finally { syncing.value = false } }
async function openDirectory() { try { await props.invoke('OpenCatalogDirectory') } catch (_) {} }
onMounted(() => { refreshFiles().catch(() => {}) })
</script>
<template>
  <main class="page-view"><div class="page-heading catalog-page-heading"><h1>配置管理</h1><div class="catalog-actions"><Tooltip title="打开配置文件夹"><Button shape="circle" aria-label="打开配置文件夹" @click="openDirectory"><template #icon><FolderOpenOutlined /></template></Button></Tooltip><Tooltip title="重新读取本地文件"><Button shape="circle" aria-label="重新读取本地文件" :loading="loading" @click="reloadCatalog"><template #icon><ReloadOutlined /></template></Button></Tooltip><Tooltip title="同步云端配置"><Button shape="circle" type="primary" aria-label="同步云端配置" :loading="syncing" @click="syncCloud"><template #icon><CloudSyncOutlined /></template></Button></Tooltip></div></div>
    <p v-if="message" class="warning-note">{{ message }}</p><section class="catalog-file-bar"><div><strong>本地配置目录</strong><span>{{ files?.directory || '正在读取…' }}</span></div><Tag color="green">项目配置</Tag><Tag color="green">任务配置</Tag><Tag color="green">关键字配置</Tag></section>
    <Tabs class="catalog-tabs" size="large"><TabPane key="project" tab="项目配置"><section class="catalog-tree"><div class="section-heading"><h2>项目（{{ projects.length }}）</h2><Button type="primary" @click="open('project')"><template #icon><PlusOutlined /></template>新增项目</Button></div><div class="catalog-item-grid"><article v-for="item in projects" :key="item.id" class="catalog-project"><div><strong>{{ item.name }}</strong><small>ID：{{ item.id }}{{ item.versions?.length ? ` · ${item.versions.join('、')}` : '' }}</small></div><span><Button shape="circle" size="small" @click="open('project', item)"><template #icon><EditOutlined /></template></Button><Button danger shape="circle" size="small" @click="remove('project', item)"><template #icon><DeleteOutlined /></template></Button></span></article></div><Empty v-if="!projects.length" description="没有项目配置" /></section></TabPane>
      <TabPane key="task" tab="任务配置"><section class="catalog-tree"><div class="section-heading"><h2>任务（{{ tasks.length }}）</h2><Button type="primary" @click="open('task')"><template #icon><PlusOutlined /></template>新增任务</Button></div><div class="catalog-item-grid"><article v-for="item in tasks" :key="item.id" class="catalog-project"><div><strong>{{ item.name }}</strong><small>{{ item.allProjects ? '全部项目' : (item.applicableProjects || []).join('、') }} · {{ item.type || 'special' }}</small></div><span><Button shape="circle" size="small" @click="open('task', item)"><template #icon><EditOutlined /></template></Button><Button danger shape="circle" size="small" @click="remove('task', item)"><template #icon><DeleteOutlined /></template></Button></span></article></div><Empty v-if="!tasks.length" description="没有任务配置" /></section></TabPane>
      <TabPane key="keywords" tab="关键字配置"><section class="catalog-tree"><div class="section-heading"><h2>关键字方案（{{ profiles.length }}）</h2><Button type="primary" @click="open('profile')"><template #icon><PlusOutlined /></template>新增方案</Button></div><article v-for="profile in profiles" :key="profile.id" class="keyword-profile"><div class="keyword-profile-head"><div><strong>{{ profile.name }}</strong><small>{{ profile.groups?.length || 0 }} 个分类 · {{ rules(profile).length }} 个关键字</small></div><span><Button shape="circle" size="small" @click="open('profile', profile)"><template #icon><EditOutlined /></template></Button><Button danger shape="circle" size="small" @click="remove('profile', profile)"><template #icon><DeleteOutlined /></template></Button><Button size="small" @click="open('group', {}, { profileId: profile.id })"><PlusOutlined />分类</Button><Button size="small" type="primary" @click="open('rule', {}, { profileId: profile.id })"><PlusOutlined />关键字</Button></span></div><div v-if="profile.rules?.length" class="keyword-group"><strong>未分类</strong><div class="keyword-rules"><div v-for="rule in profile.rules" :key="rule.id" class="keyword-rule"><div><b>{{ rule.name }}</b><span>{{ rule.match }}</span></div><span><Tag v-if="rule.mode === 'regex'">正则</Tag><Button shape="circle" size="small" @click="open('rule', rule, { profileId: profile.id })"><template #icon><EditOutlined /></template></Button><Button danger shape="circle" size="small" @click="remove('rule', rule, { profileId: profile.id })"><template #icon><DeleteOutlined /></template></Button></span></div></div></div><div v-for="group in profile.groups || []" :key="group.id" class="keyword-group"><div class="keyword-group-head"><strong>{{ group.name }}</strong><span><small v-if="group.scope">{{ group.scope }}</small><Button shape="circle" size="small" @click="open('group', group, { profileId: profile.id })"><template #icon><EditOutlined /></template></Button><Button danger shape="circle" size="small" @click="remove('group', group, { profileId: profile.id })"><template #icon><DeleteOutlined /></template></Button><Button size="small" @click="open('rule', {}, { profileId: profile.id, groupId: group.id })"><PlusOutlined />关键字</Button></span></div><div class="keyword-rules"><div v-for="rule in group.rules || []" :key="rule.id" class="keyword-rule"><div><b>{{ rule.name }}</b><span>{{ rule.match }}</span></div><span><Tag v-if="rule.mode === 'regex'">正则</Tag><Button shape="circle" size="small" @click="open('rule', rule, { profileId: profile.id, groupId: group.id })"><template #icon><EditOutlined /></template></Button><Button danger shape="circle" size="small" @click="remove('rule', rule, { profileId: profile.id, groupId: group.id })"><template #icon><DeleteOutlined /></template></Button></span></div><Empty v-if="!group.rules?.length" description="暂无关键字" /></div></div></article><Empty v-if="!profiles.length" description="没有关键字配置" /></section></TabPane></Tabs>
    <Modal v-model:open="dialog.open" :title="dialogTitle()" ok-text="保存" :confirm-loading="loading" @ok="save"><Form layout="vertical"><FormItem label="稳定 ID"><Input v-model:value="form.id" :disabled="dialog.editing" /></FormItem><FormItem label="名称"><Input v-model:value="form.name" /></FormItem><template v-if="dialog.kind === 'project'"><FormItem label="可用版本"><Input v-model:value="form.versionsText" placeholder="用逗号分隔" /></FormItem></template><template v-if="dialog.kind === 'task'"><FormItem label="任务类型"><Input v-model:value="form.type" /></FormItem><FormItem><Checkbox v-model:checked="form.allProjects">适用于全部项目</Checkbox></FormItem><FormItem v-if="!form.allProjects" label="适用项目"><Select v-model:value="form.applicableProjects" mode="multiple" :options="projects.map((x) => ({ value: x.id, label: x.name }))" /></FormItem></template><template v-if="dialog.kind === 'group'"><FormItem label="范围"><Input v-model:value="form.scope" placeholder="选填" /></FormItem></template><template v-if="dialog.kind === 'rule'"><FormItem label="匹配文字"><Input v-model:value="form.match" /></FormItem><FormItem label="匹配方式"><Select v-model:value="form.mode" :options="[{ value: 'contains', label: '普通包含' }, { value: 'regex', label: '正则表达式' }]" /></FormItem><FormItem><Checkbox v-model:checked="form.caseSensitive">区分大小写</Checkbox></FormItem></template></Form></Modal>
  </main>
</template>
